package com.visa.req.visareq;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AppCredit implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Applicant Credit")
   private java.lang.String applicantCredit;

   public AppCredit()
   {
   }

   public java.lang.String getApplicantCredit()
   {
      return this.applicantCredit;
   }

   public void setApplicantCredit(java.lang.String applicantCredit)
   {
      this.applicantCredit = applicantCredit;
   }

   public AppCredit(java.lang.String applicantCredit)
   {
      this.applicantCredit = applicantCredit;
   }

}