package com.visa.req.visareq;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AutoEval implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Auto Evaluation")
   private java.lang.String autoEvaluation;

   public AutoEval()
   {
   }

   public java.lang.String getAutoEvaluation()
   {
      return this.autoEvaluation;
   }

   public void setAutoEvaluation(java.lang.String autoEvaluation)
   {
      this.autoEvaluation = autoEvaluation;
   }

   public AutoEval(java.lang.String autoEvaluation)
   {
      this.autoEvaluation = autoEvaluation;
   }

}