package com.visa.req.visareq;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ManagerApproval implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Manager Approve")
   private Boolean managerApprove;

   public ManagerApproval()
   {
   }

   public java.lang.Boolean getManagerApprove()
   {
      return this.managerApprove;
   }

   public void setManagerApprove(java.lang.Boolean managerApprove)
   {
      this.managerApprove = managerApprove;
   }

   public ManagerApproval(java.lang.Boolean managerApprove)
   {
      this.managerApprove = managerApprove;
   }

}