package com.visa.req.visareq;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class visasubmite implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Name")
   private java.lang.String name;

   @org.kie.api.definition.type.Label("Current Job")
   private java.lang.String job;

   @org.kie.api.definition.type.Label("Current Salary")
   private java.math.BigInteger salary;

   @org.kie.api.definition.type.Label("Gender")
   private String gender;

   @org.kie.api.definition.type.Label("Visa Limit")
   private java.math.BigInteger visalimit;

   @org.kie.api.definition.type.Label("Second Check")
   private java.lang.Boolean secondcheck;

   @org.kie.api.definition.type.Label("Manager Approval")
   private java.lang.Boolean managerapp;

   @org.kie.api.definition.type.Label("First Pass")
   private java.lang.Boolean firstPass;

   @org.kie.api.definition.type.Label(value = "Manager Approve")
   private java.lang.Boolean managerApprove;

   public visasubmite()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getJob()
   {
      return this.job;
   }

   public void setJob(java.lang.String job)
   {
      this.job = job;
   }

   public java.math.BigInteger getSalary()
   {
      return this.salary;
   }

   public void setSalary(java.math.BigInteger salary)
   {
      this.salary = salary;
   }

   public java.math.BigInteger getVisalimit()
   {
      return this.visalimit;
   }

   public void setVisalimit(java.math.BigInteger visalimit)
   {
      this.visalimit = visalimit;
   }

   public java.lang.Boolean getSecondcheck()
   {
      return this.secondcheck;
   }

   public void setSecondcheck(java.lang.Boolean secondcheck)
   {
      this.secondcheck = secondcheck;
   }

   public java.lang.Boolean getManagerapp()
   {
      return this.managerapp;
   }

   public void setManagerapp(java.lang.Boolean managerapp)
   {
      this.managerapp = managerapp;
   }

   public java.lang.Boolean getFirstPass()
   {
      return this.firstPass;
   }

   public void setFirstPass(java.lang.Boolean firstPass)
   {
      this.firstPass = firstPass;
   }

   public java.lang.String getGender()
   {
      return this.gender;
   }

   public void setGender(java.lang.String gender)
   {
      this.gender = gender;
   }

   public java.lang.Boolean getManagerApprove()
   {
      return this.managerApprove;
   }

   public void setManagerApprove(java.lang.Boolean managerApprove)
   {
      this.managerApprove = managerApprove;
   }

   public visasubmite(java.lang.String name, java.lang.String job,
         java.math.BigInteger salary, java.lang.String gender,
         java.math.BigInteger visalimit, java.lang.Boolean secondcheck,
         java.lang.Boolean managerapp, java.lang.Boolean firstPass,
         java.lang.Boolean managerApprove)
   {
      this.name = name;
      this.job = job;
      this.salary = salary;
      this.gender = gender;
      this.visalimit = visalimit;
      this.secondcheck = secondcheck;
      this.managerapp = managerapp;
      this.firstPass = firstPass;
      this.managerApprove = managerApprove;
   }

}